name: budgetblud
description: "A new Flutter project."
publish_to: 'none' # private package
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/pic1.png
    - images/pic2.png
    - images/pic3.png
    - images/set1.png
    - images/set2.png
    - images/budget_blud.png